site_name: Super Chasm Hunter
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  language: it
  features:
    - navigation.top
    - navigation.footer
  plugins:
    - search
    - search.suggest
  repo_url: https://github.com/FilippoGurioli/super-chasm-hunter-pm
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: green
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: light green
      accent: light green
      toggle:
        icon: material/brightness-2
        name: Switch to light mode
extra:
  generator: false

