site_name: Super Chasm Hunter
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  language: it
  features:
    - navigation.top
  # test
  markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.keys
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  # test
  plugins:
    - search
    - search.suggest
    - mermaid2
  repo_url: https://github.com/FilippoGurioli/super-chasm-hunter-pm
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: green
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: green
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to light mode

